### ISSUE TITLE
Test IT table 1

### ISSUE THREAD

**Issue by tingyuw** [gabrielasd/eomee#18] opened 2020-11-04 07:16 UTC
I was looking at table 1 and I think it is a little bit confusing. Like what does the input set wrong means? Does it mean the wrong type of error in each set(S1, S2)? Although your input seems to be generated randomly, you still can feed some specific values to the test cases and show exactly what kind of type values will let the software display an error message. I mean, your output is showing a type-error in each case, but I don't quite understand what kind of error it is for each case and why it is wrong. You might want to make the table much clearly.

**Comment by gabrielasd** [comment] 2020-11-05 01:29
Hello @tingyuw,
You are right, I should have made a better description of this table, thanks for pointing this out.

The **Wrong** row was intended at clarifying what mistake the user had made in each input set:
S1: a tuple was inputted
S2: a list was inputted
The EOMEE code will check that the input variables type is a NumPy array, and raise a type error exception when this requirement is not meet.
The test will verify that indeed this error is raised by the cases S1 and S2

**Comment by gabrielasd** [comment] 2020-12-09 22:19
Clarifying System Tests tables description:
I've extended the descriptions in the Input sections and table captions of the system tests in Section 5.1.1 and subsection Transition energies. Hopefully, this makes the test cases clearer.
The fix is included in commit da2916654d6242aa2890b0fbd3abfc88ca1f1e7b
This modification relates also to issues #19 and #20

**Closed by gabrielasd** 2020-12-09 22:20 UTC
